engines: 
  eslint:
    enabled: true
    channel: "eslint-3"
  duplication:
    enabled: true

ratings:
    paths:
    - "build/**/*"
    - "generators/**/*"
    - test
exclude_paths:
- coverage
- testresults
- node_modules
- "generators/app/templates/**/*"
