language: java
jdk:
  - oraclejdk8

os:
  - linux

addons:
  srcclr: true
  code_climate: true
  sonarqube:
    token:
      secure: '$SONAR_TOKEN'

cache:
  directories:
    - '$HOME/.sonar/cache'

before_script:
    - export PROJECT_VERSION=$(node -e "console.log(require('./package.json').version);")

install:    
    - nvm install node
    - npm install
    - nvm install 6
    - nvm install 5
    - nvm install 4

script:
    - nvm use 4
    - npm run lint
    - npm run enforce-code-coverage
    - nvm use 5
    - npm run lint
    - npm run enforce-code-coverage
    - nvm use 6
    - npm run lint
    - npm run enforce-code-coverage
    - nvm use node
    - npm run lint
    - npm run enforce-code-coverage
    - sonar-scanner -D sonar.projectVersion=$PROJECT_VERSION   
