language: java
jdk:
  - oraclejdk8

os:
  - linux

addons:
  srcclr: true
  sonarqube:
    token:
      secure: '$SONAR_TOKEN'

cache:
  directories:
    - '$HOME/.sonar/cache'

before_script:
    - export PROJECT_VERSION=$(node -e "console.log(require('./package.json').version);")
    - echo $PROJECT_VERSION
    - echo $JAVA_HOME
    - echo $TRAVIS_JDK_VERSION

install:
    - nvm install node
    - nvm install 6
    - nvm install 5
    - nvm install 4

script:
    - nvm use node
    - npm run-script lint
    - npm run-script enforce-code-coverage
    - sonar-scanner -D sonar.projectVersion=$PROJECT_VERSION
    - nvm use 6
    - npm run lint
    - npm run enforce-code-coverage
    - nvm use 5
    - npm run lint
    - npm run enforce-code-coverage
    - nvm use 4
    - npm run lint
    - npm run enforce-code-coverage
