language: node_js
node_js:
  - "node"
  - "6"
  - "5"
  - "4"

os:
  - linux

addons:
  srcclr: true
  sonarqube:
    token:
      secure: '$SONAR_TOKEN'

cache:
  directories:
    - '$HOME/.sonar/cache'

jdk:
  - oraclejdk8

before_script:
    - export PROJECT_VERSION=$(node -e "console.log(require('./package.json').version);")

script:
    - npm run lint
    - npm run enforce-code-coverage
    - sonar-scanner -D sonar.projectVersion=$PROJECT_VERSION
