language: java
jdk:
  - oraclejdk8

os:
  - linux

addons:
  srcclr: true
  codeclimate:
    repo_token: $CODECLIMATE_TOKEN
  sonarqube:
    token:
      secure: $SONAR_TOKEN

cache:
  directories:
    - '$HOME/.sonar/cache'

before_script:
    - export PROJECT_VERSION=$(node -e "console.log(require('./package.json').version);")

install:  
    - nvm install node
    - npm install
    - npm install -g codeclimate-test-reporter
    - nvm install 6
    - nvm install 5
    - nvm install 4

script:
    - nvm use 4
    - npm run lint
    - npm run enforce-code-coverage
    - nvm use 5
    - npm run lint
    - npm run enforce-code-coverage
    - nvm use 6
    - npm run lint
    - npm run enforce-code-coverage
    - nvm use node
    - npm run lint
    - npm run enforce-code-coverage
    - if [ "$SONARQUBE_SKIPPED" != true ]; then sonar-scanner -D sonar.projectVersion=$PROJECT_VERSION; fi

after_success:
    - codeclimate-test-reporter < coverage/unit/lcov.info
